# Generated by Django 4.2.16 on 2025-06-08 11:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAbst', '0002_customuser_created_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='classe',
            name='description',
        ),
        migrations.AddField(
            model_name='classe',
            name='capacite_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='eleve',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='actif',
            field=models.BooleanField(default=True, help_text="Cochez si l'élève est actuellement inscrit", verbose_name='Élève actif'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='gestionAbst.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(help_text='Format: JJ/MM/AAAA', verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='email_parent',
            field=models.EmailField(blank=True, help_text='Adresse email du parent (optionnel)', max_length=254, null=True, verbose_name='Email parent'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='matricule',
            field=models.CharField(help_text="Matricule unique de l'élève", max_length=20, unique=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom',
            field=models.CharField(help_text="Nom de famille de l'élève", max_length=50, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nom_parent',
            field=models.CharField(help_text='Nom complet du parent ou tuteur légal', max_length=100, verbose_name='Nom du parent/tuteur'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='prenoms',
            field=models.CharField(help_text="Prénoms de l'élève (séparés par des espaces)", max_length=100, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(help_text='Numéro de téléphone du parent/tuteur', max_length=15, validators=[django.core.validators.RegexValidator(message="Format attendu: '+225XXXXXXXX' ou '0XXXXXXXX'", regex='^\\+?225?\\d{8,10}$')], verbose_name='Téléphone parent'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['matricule'], name='gestionAbst_matricu_93c7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['nom', 'prenoms'], name='gestionAbst_nom_743369_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['classe', 'actif'], name='gestionAbst_classe__07fa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='eleve',
            index=models.Index(fields=['created_at'], name='gestionAbst_created_be33f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='eleve',
            constraint=models.CheckConstraint(check=models.Q(('date_naissance__lte', datetime.date(2025, 6, 8))), name='date_naissance_valide'),
        ),
    ]
