# Generated by Django 4.2.16 on 2025-06-14 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAbst', '0003_alter_classe_options_remove_classe_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.RemoveConstraint(
            model_name='eleve',
            name='date_naissance_valide',
        ),
        migrations.AddField(
            model_name='presence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='sms_envoye',
            field=models.BooleanField(default=False, help_text='Indique si un SMS a été envoyé pour cette note'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='sms_envoye',
            field=models.BooleanField(default=False, help_text='Indique si un SMS a été envoyé pour cette absence'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='statut',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], default='present', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='eleve',
            constraint=models.CheckConstraint(check=models.Q(('date_naissance__lte', datetime.date(2025, 6, 14))), name='date_naissance_valide'),
        ),
    ]
